---
- name: Configure Gitaly settings
  ansible.builtin.template:
    dest: "{{ gitlab_config }}"
    src: gitlab.rb.j2
    owner: root
    group: root
    mode: '0600'
  notify:
    - gitlab_reconfigure
    - gitlab_restart
