---
- name: Make gitaly partition
  community.general.parted:
    device: "{{ gitlab_gitaly_disk }}"
    number: 1
    state: present
    fs_type: xfs

- name: Create gitaly filesystem
  community.general.filesystem:
    fstype: xfs
    dev: "{{ gitlab_gitaly_disk }}1"

- name: Create a directory if it does not exist
  file:
    path: "{{ gitlab_gitaly_datadir }}"
    state: directory
    owner: git
    group: root
    mode: '0700'

- name: Mount up gitaly directory
  ansible.posix.mount:
    path: "{{ gitlab_gitaly_datadir }}"
    src: "{{ gitlab_gitaly_disk }}1"
    fstype: xfs
    state: present
