---
- name: Install dependencies
  apt:
    name: "{{ gitlab_gitaly_dependencies }}"
    state: present

- name: Make gitaly partition
  community.general.parted:
    device: "{{ gitlab_gitaly_disk }}"
    number: 1
    state: present
    fs_type: xfs

- name: Create gitaly filesystem
  community.general.filesystem:
    fstype: xfs
    dev: "{{ gitlab_gitaly_disk }}1"

- name: Create a directory if it does not exist
  file:
    path: "{{ gitlab_gitaly_datadir }}"
    state: directory
    mode: '0755'

- name: Mount up gitaly directory
  ansible.posix.mount:
    path: "{{ gitlab_gitaly_datadir }}"
    src: "{{ gitlab_gitaly_disk }}1"
    fstype: xfs
    state: present

- name: Add an Apt signing key
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
    state: present

- name: Add gitlab repository into sources list
  apt_repository:
    repo: deb https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/ focal main
    state: present

- name: Install gitlab-ee package
  apt:
    name: "{{ gitlab_packages }}"
    state: present
    update_cache: yes

- name: Configure Gitaly settings
  ansible.builtin.template:
    dest: "{{ gitlab_config }}"
    src: gitlab.rb.j2
    owner: root
    group: root
    mode: '0600'
  register: gitlab_gitaly
  notify:
    - gitlab_restart

- name: gitlab_reconfigure
  command:
    cmd: "{{ gitlab_ctl }} reconfigure"
  async: 300
  poll: 20
  when: gitlab_gitaly
