---
- name: gitlab_reconfigure
  command:
    cmd: "{{ gitlab_ctl }} reconfigure"
  async: 300
  poll: 20

- name: gitlab_restart
  command:
    cmd: "{{ gitlab_ctl }} restart"
  async: 300
  poll: 20
